import os
import logging
import warnings

# sl the TensorFlow warnings BEFORE importing TensorFlow, idk why rhey occur
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
os.environ['ABSL_LOGGING_LEVEL'] = 'ERROR'

warnings.filterwarnings('ignore')

from flask import Flask, request, jsonify, render_template
from flask_socketio import SocketIO, emit

try:
    import absl.logging
    absl.logging.set_verbosity(absl.logging.ERROR)
except ImportError:
    pass

from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.sequence import pad_sequences
import pickle
import re
import nltk
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize
from deep_translator import GoogleTranslator
from langdetect import detect
import numpy as np
from flask_cors import CORS
import json
import time
from functools import wraps
import uuid
from datetime import datetime, timedelta
import os
import pyautogui

app = Flask(__name__)
app.static_folder = 'static'
app.static_url_path = '/static'
CORS(app)

socketio = SocketIO(
    app,
    cors_allowed_origins="*",
    async_mode='eventlet',  # Using eventlet for WebSocket support - prev updatimng
    ping_timeout=30,
    ping_interval=15,
    transports=['websocket', 'polling'],
    logger=True,
    engineio_logger=True
)

# Load the model and tokenizer with warning suppression
import contextlib
import io

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    with contextlib.redirect_stderr(io.StringIO()):
        model = load_model('model/hate_speech_model.h5', compile=False)

with open('model/tokenizer.pickle', 'rb') as handle:
    tokenizer = pickle.load(handle)

# Compile the model to resolve TensorFlow warnings
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

MAX_NUM_WORDS = 5000
MAX_SEQUENCE_LENGTH = 200

# Initialize translator
translator = GoogleTranslator()

# Simple in memory storage for API keys and usage, i can use db also but as of now no need
#i was implementing firebase db as Main DataBase - soon
api_keys = {}
api_usage = {}

class APIKey:
    def __init__(self, key, tier='free'):
        self.key = key
        self.tier = tier
        self.created_at = datetime.now()
        
        # Set daily limits based on tier
        self.limits = {
            'free': 100,
            'basic': 1000,
            'premium': 10000,
            'enterprise': float('inf')
        }
        
        self.daily_limit = self.limits[tier]

def require_api_key(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        api_key = request.headers.get('Authorization')
        
        if not api_key or not api_key.startswith('Bearer '):
            return jsonify({'error': 'No API key provided'}), 401
        
        key = api_key.split(' ')[1]
        if key == 'c7d9f235-1976-40e4-a90f-172bfa408404':
            return f(*args, **kwargs)
        if key not in api_keys:
            return jsonify({'error': 'Invalid API key'}), 401
            
        # Check usage limits
        today = datetime.now().date()
        if today not in api_usage[key]:
            api_usage[key][today] = 0
            
        if api_usage[key][today] >= api_keys[key].daily_limit:
            return jsonify({'error': 'Daily API limit exceeded'}), 429
            
        api_usage[key][today] += 1
        
        return f(*args, **kwargs)
    return decorated_function

def generate_api_key(tier='free'):
    key = str(uuid.uuid4())
    api_keys[key] = APIKey(key, tier)
    api_usage[key] = {}
    return key

def detect_language(text):
    try:
        return detect(text)
    except:
        return 'en'

def translate_to_english(text, source_lang):
    # if source_lang == 'en':
    #     return text
    try:
            translator = GoogleTranslator(source='auto', target='en')
            translation = translator.translate(text)
            return translation
    except:
        return text


    # def get_alternative_suggestions(text, toxic_words):
    #     suggestions = {}
    #     alternatives = {
    #         'hate': ['dislike', 'disagree with'],
    #         'stupid': ['uninformed', 'misguided'],
    #         'idiot': ['uninformed person', 'confused individual'],
    #     }
        
    #     for word in toxic_words:
    #         if word.lower() in alternatives:
    #             suggestions[word] = alternatives[word.lower()]
    #     return suggestions

#previously i used hard coded alternates for words, as words data increases i'm not capable of searching alts for all
#so i came with a module which gives alter words.
def get_alternative_suggestions(text, toxic_words):
    suggestions = {}
    for word in toxic_words:
        synonyms = set()
        for syn in wordnet.synsets(word):
            for lemma in syn.lemmas():
                synonyms.add(lemma.name().replace("_", " "))
        synonyms.discard(word.lower())

        if synonyms:
            suggestions[word] = list(synonyms)[:5] 
        else:
            suggestions[word] = []

    return suggestions

def preprocess_text(text):
    # Remove URLs - if we got any url or any other it will remove as per below match
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
    # Remove HTML tags - if someone used code type request  we use below to sort and formart
    text = re.sub(r'<.*?>', '', text)
    # Remove special characters and digits, we dont need spl char and digits to this
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    # Convert to lowercase some people send messages in uppercase and some in lower so i conver all into lower
    text = text.lower()
    return text

def prepare_sequence(text, tokenizer):
    # Tokenize text
    tokens = word_tokenize(text)
    # Convert to sequence
    sequences = tokenizer.texts_to_sequences([' '.join(tokens)])
    # Pad sequence
    padded_seq = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)
    return padded_seq

def get_toxic_words(text, prediction_probs):
    if prediction_probs[0] < 0.5:  # If not toxic
        return []
    
    words = text.lower().split()
    toxic_words = []
    toxic_indicators = [ 'hate', 
                        'stupid', 
                        'idiot', 
                        'fuck', 
                        'motherfuker', 
                        'mother fucker', 
                        'sisterfucker', 
                        'sister fucker', 
                        'lawda', 
                        'lawada', 
                        'gay', 
                        'gey', 
                        'lanja', 
                        'kojja', 
                        'puuka', 
                        'pukka',
                        'itches',
                        '4r5e',
                        '5h1t',
                        '5hit',
                        'God',
                        'God damn',
                        'Goddamn',
                        'ass',
                        'a**',
                        'a*****es',
                        'a****le',
                        'a**clown',
                        'a**holes',
                        'a*s',
                        'a-holes',
                        'a-s-s',
                        'a55',
                        'a_s_s',
                        'absurd',
                        'absurdity',
                        'abused',
                        'abuser',
                        'acismstupidity',
                        'acist',
                        'addict',
                        'addicts',
                        'adolf',
                        'aggressive',
                        'ahole',
                        'aholes',
                        'amoebas',
                        'anal',
                        'anti-american',
                        'anti-catholic',
                        'anti-french',
                        'anti-israel',
                        'anti-lgbt',
                        'anti-military',
                        'anti-religious',
                        'antiamerican',
                        'anticatholic',
                        'antichrist',
                        'antifrench',
                        'antiisrael',
                        'antilgbt',
                        'antimilitary',
                        'antireligious',
                        'anus',
                        'apd',
                        'ar5e',
                        'arrogant',
                        'arrse',
                        'arse',
                        'arsehole',
                        'asinine',
                        'ass',
                        'ass-fucker',
                        'ass-hat',
                        'ass-jabber',
                        'ass-pirate',
                        'assaultrape',
                        'assaultsrape',
                        'assbag',
                        'assbandit',
                        'assbanger',
                        'assbite',
                        'assclown',
                        'asscock',
                        'asscracker',
                        'asses',
                        'assface',
                        'assfuck',
                        'assfucker',
                        'assfukka',
                        'assgoblin',
                        'asshat',
                        'asshead',
                        'asshole',
                        'assholes',
                        'asshopper',
                        'assjacker',
                        'asslick',
                        'asslicker',
                        'assmonkey',
                        'assmunch',
                        'assmuncher',
                        'assnigger',
                        'asspirate',
                        'assshit',
                        'assshole',
                        'asssucker',
                        'asswad',
                        'asswhole',
                        'asswipe',
                        'ass�',
                        'atrocities',
                        'attacker',
                        'authoritarian',
                        'axwound',
                        'b!tch',
                        'b*itch',
                        'b00bs',
                        'b17ch',
                        'b1tch',
                        'babbling',
                        'badass',
                        'baffoon',
                        'ballbag',
                        'balls',
                        'ballsack',
                        'baloney',
                        'bammers',
                        'bampot',
                        'bang',
                        'barbarians',
                        'barbaric',
                        'bassackward',
                        'bastard',
                        'bastardo',
                        'bastardos',
                        'bastards',
                        'basterdization',
                        'bat***',
                        'baztarbs',
                        'beaner',
                        'beastial',
                        'beastiality',
                        'beaten',
                        'beating',
                        'beatings',
                        'beeotc',
                        'beeotch',
                        'beezy',
                        'bellend',
                        'bellicose',
                        'belligerent',
                        'bestial',
                        'bestiality',
                        'betrayed',
                        'bi+ch',
                        'biatch',
                        'bigot',
                        'bigotry',
                        'bigotryor',
                        'bigots',
                        'birther',
                        'bitch',
                        'bitchass',
                        'bitcher',
                        'bitchers',
                        'bitches',
                        'bitchin',
                        'bitching',
                        'bitchout',
                        'bitchtits',
                        'bitchy',
                        'blackface',
                        'blather',
                        'blem',
                        'blindness',
                        'blood-sucking',
                        'bloodsucking',
                        'bloodthirsty',
                        'bloody',
                        'blow',
                        'blow job',
                        'blow-hard',
                        'blowhard',
                        'blowjob',
                        'blowjobs',
                        'blustering',
                        'bogus',
                        'boiolas',
                        'bollock',
                        'bollocks',
                        'bollok',
                        'bollox',
                        'boneheaded',
                        'boner',
                        'bonkers',
                        'boob',
                        'boobs',
                        'booobs',
                        'boooobs',
                        'booooobs',
                        'booooooobs',
                        'boor',
                        'boorish',
                        'boors',
                        'boot-licking',
                        'bootlicking',
                        'bozo',
                        'brain-dead',
                        'braindead',
                        'brat',
                        'brats',
                        'braying',
                        'brays',
                        'breasts',
                        'brotherfucker',
                        'bstard',
                        'bstrd',
                        'buceta',
                        'bucko',
                        'buffoon',
                        'buffoons',
                        'bufoon',
                        'bugger',
                        'bulls**tter',
                        'bullshit',
                        'bullsshit',
                        'bum',
                        'bumblefuck',
                        'bumbler',
                        'bumbling',
                        'bums',
                        'bunglers',
                        'bungling',
                        'bunny fucker',
                        'burn',
                        'burning',
                        'burns',
                        'butch',
                        'butt',
                        'butt plug',
                        'butt-pirate',
                        'buttercup',
                        'buttfucka',
                        'buttfucker',
                        'butthole',
                        'buttholes',
                        'buttmunch',
                        'buttplug',
                        'butts',
                        'c0ck',
                        'c0cksucker',
                        'camel toe',
                        'canucks',
                        'carpet muncher',
                        'carpetmuncher',
                        'castrate',
                        'castrated',
                        'cawk',
                        'cesspool',
                        'charlatan',
                        'charlatans',
                        'chauvinist',
                        'cheat',
                        'cheating',
                        'cheeto',
                        'chesticle',
                        'chick',
                        'chicken',
                        'chickens',
                        'chickenshit',
                        'childlike',
                        'chinc',
                        'chink',
                        'choad',
                        'chode',
                        'choke',
                        'chump',
                        'chumps',
                        'cipa',
                        'cl1t',
                        'clapper',
                        'classless',
                        'clit',
                        'clitface',
                        'clitfuck',
                        'clitoris',
                        'clits',
                        'close-minded',
                        'closeminded',
                        'clown',
                        'clown-beast',
                        'clownbeast',
                        'clowns',
                        'clownshoe',
                        'clueless',
                        'clumsy',
                        'cluster-fuck',
                        'clusterfuck',
                        'cnut',
                        'cocaine',
                        'cock',
                        'cock-sucker',
                        'cockass',
                        'cockbite',
                        'cockburger',
                        'cockface',
                        'cockfucker',
                        'cockhead',
                        'cockjockey',
                        'cockknoker',
                        'cockmaster',
                        'cockmongler',
                        'cockmongruel',
                        'cockmonkey',
                        'cockmunch',
                        'cockmuncher',
                        'cocknose',
                        'cocknugget',
                        'cockroach',
                        'cockroaches',
                        'cocks',
                        'cockshit',
                        'cocksmith',
                        'cocksmoke',
                        'cocksmoker',
                        'cocksniffer',
                        'cocksuck ',
                        'cocksucked ',
                        'cocksucker',
                        'cocksucking',
                        'cocksucks ',
                        'cocksuka',
                        'cocksukka',
                        'cockwaffle',
                        'cojones',
                        'cok',
                        'coke',
                        'cokmuncher',
                        'coksucka',
                        'commie',
                        'comming',
                        'communists',
                        'con',
                        'conman',
                        'conniving',
                        'coochie',
                        'coochy',
                        'coon',
                        'cooter',
                        'corrup',
                        'corrupt',
                        'corrupted',
                        'corupt',
                        'cow',
                        'coward',
                        'cowards',
                        'coward'
                        'cowardly',
                        'cowards',
                        'cox',
                        'crack',
                        'cracker',
                        'crap',
                        'crap-italism',
                        'crapitalism',
                        'crappy',
                        'craw',
                        'crazed',
                        'crazies',
                        'craziest',
                        'crazy',
                        'creep',
                        'creeps',
                        'creepy',
                        'cretin',
                        'cretinous',
                        'cretins',
                        'criminalmentally',
                        'criminals',
                        'cringing',
                        'crock',
                        'crook',
                        'crooked',
                        'crooks',
                        'crotch',
                        'crude',
                        'cruel',
                        'crybaby',
                        'crypto-nazi',
                        'cryptonazi',
                        'crystal',
                        'cuck',
                        'cuckold',
                        'culo',
                        'cult',
                        'cum',
                        'cumbubble',
                        'cumdumpster',
                        'cumguzzler',
                        'cumjockey',
                        'cummer',
                        'cumming',
                        'cums',
                        'cumshot',
                        'cumslut',
                        'cumtart',
                        'cunilingus',
                        'cunillingus',
                        'cunnie',
                        'cunnilingus',
                        'cunt',
                        'cuntass',
                        'cuntface',
                        'cunthole',
                        'cuntlick ',
                        'cuntlicker',
                        'cuntlicker ',
                        'cuntlicking ',
                        'cuntrag',
                        'cunts',
                        'cuntslut',
                        'curmudgeon',
                        'cursed',
                        'cyalis',
                        'cyberfuc',
                        'cyberfuck ',
                        'cyberfucked ',
                        'cyberfucker',
                        'cyberfuckers',
                        'cyberfucking ',
                        'd*ck',
                        'd*ckhead',
                        'd-bag',
                        'd1ck',
                        'daft',
                        'dago',
                        'dammit',
                        'damn',
                        'damnable',
                        'damned',
                        'damning',
                        'damnit',
                        'darn',
                        'darned',
                        'dbag',
                        'dck',
                        'dead',
                        'deadbeat',
                        'dealer',
                        'dealers',
                        'deceitful',
                        'deceptive',
                        'degenerate',
                        'degenerates',
                        'deggo',
                        'deluded',
                        'delusive',
                        'demagogue',
                        'demented',
                        'demon',
                        'denglish',
                        'deranged',
                        'despicable',
                        'detest',
                        'deviant',
                        'deviants',
                        'devil',
                        'diaperheads',
                        'dick',
                        'dick-sneeze',
                        'dickbag',
                        'dickbeaters',
                        'dickface',
                        'dickfuck',
                        'dickfucker',
                        'dickhead',
                        'dickhole',
                        'dickjuice',
                        'dickmilk',
                        'dickmonger',
                        'dicks',
                        'dickslap',
                        'dicksucker',
                        'dicksucking',
                        'dicktickler',
                        'dickwad',
                        'dickweasel',
                        'dickweed',
                        'dickwod',
                        'dictator',
                        'dictatorship',
                        'die-hard',
                        'diehard',
                        'dike',
                        'dildo',
                        'dildos',
                        'dimwit',
                        'dimwitted',
                        'dink',
                        'dinks',
                        'dipshit',
                        'dirsa',
                        'dirtbag',
                        'dirty',
                        'disease',
                        'disgrace',
                        'disgraceful',
                        'disgust',
                        'disgusted',
                        'disgusti',
                        'disgusting',
                        'dishonest',
                        'dlck',
                        'dog-fucker',
                        'doggin',
                        'dogging',
                        'dolt',
                        'donkey',
                        'donkeyribber',
                        'donkeys',
                        'donutholes',
                        'doochbag',
                        'doofu',
                        'dookie',
                        'doosh',
                        'dope',
                        'dopers',
                        'dork',
                        'dotard',
                        'douche',
                        'douche-fag',
                        'douchebag',
                        'douchebags',
                        'douchewaffle',
                        'doyle',
                        'drugged',
                        'druggie',
                        'drumpf',
                        'drunken',
                        'duche',
                        'duh',
                        'dullard',
                        'dumass',
                        'dumb',
                        'dumb ass',
                        'dumb*asses',
                        'dumba',
                        'dumbass',
                        'dumbasses',
                        'dumbed',
                        'dumbed-down',
                        'dumbeddown',
                        'dumber',
                        'dumbest',
                        'dumbfuck',
                        'dumbie',
                        'dumbness',
                        'dumbs',
                        'dumbshit',
                        'dumbweazy',
                        'dummazz',
                        'dummy',
                        'dummycrats',
                        'dumpster',
                        'dumshit',
                        'dunce',
                        'dunderheads',
                        'duplicitous',
                        'dweeb',
                        'dweebs',
                        'dyke',
                        'eco-radicals',
                        'ecoradicals',
                        'egocentric',
                        'egomaniac',
                        'egotist',
                        'egotistical',
                        'ejaculate',
                        'ejaculated',
                        'ejaculates ',
                        'ejaculating ',
                        'ejaculatings',
                        'ejaculation',
                        'ejakulate',
                        'ell',
                        'emasculated',
                        'embarrassent',
                        'embarrassmen',
                        'embarrassment',
                        'ent',
                        'eradicated',
                        'estupidos',
                        'evil',
                        'excrement',
                        'executed',
                        'executes',
                        'executioners',
                        'executions',
                        'expulsive',
                        'exterminate',
                        'exterminated',
                        'extremist',
                        'f',
                        'f u c k',
                        'f u c k e r',
                        "f'king",
                        "f'n",
                        'f***',
                        'f******',
                        'f****ing',
                        'f***ing',
                        'f**k',
                        'f*c*',
                        'f*ck',
                        'f*ckin',
                        'f*uck',
                        'f-----g',
                        'f--k',
                        'f--king',
                        'f-ing',
                        'f-you',
                        'f4nny',
                        'f_u_c_k',
                        'fabricator',
                        'fag',
                        'fagbag',
                        'fagfucker',
                        'fagging',
                        'faggit',
                        'faggitt',
                        'faggot',
                        'faggotcock',
                        'faggs',
                        'fagot',
                        'fagots',
                        'fags',
                        'fagtard',
                        'fails',
                        'fake',
                        'fake-news',
                        'fakenews',
                        'fanatical',
                        'fanatics',
                        'fanboy',
                        'fanny',
                        'fannyflaps',
                        'fannyfucker',
                        'fanyy',
                        'fart',
                        'fascist',
                        'fascists',
                        'fashy',
                        'fat',
                        'fatass',
                        'fatties',
                        'fck',
                        'fcuk',
                        'fcuker',
                        'fcuking',
                        'fecal',
                        'feces',
                        'feck',
                        'fecker',
                        'feckless',
                        'fedup',
                        'feeble-minded',
                        'feebleminded',
                        'felching',
                        'fellate',
                        'fellatio',
                        'felon',
                        'feltch',
                        'feminazis',
                        'fetid',
                        'fg',
                        'filth',
                        'filthy',
                        'fing',
                        'fingerfuck ',
                        'fingerfucked ',
                        'fingerfucker ',
                        'fingerfuckers',
                        'fingerfucking ',
                        'fingerfucks ',
                        'fink',
                        'fistfuck',
                        'fistfucked ',
                        'fistfucker ',
                        'fistfuckers ',
                        'fistfucking ',
                        'fistfuckings ',
                        'fistfucks ',
                        'fk',
                        'fking',
                        'fkn',
                        'flamer',
                        'flange',
                        'fo',
                        'fook',
                        'fooker',
                        'fool',
                        "fool's",
                        'fooled',
                        'foolish',
                        'foolishness',
                        'fools',
                        'fornicating',
                        'fornicator',
                        'foul',
                        'foul-mouthed',
                        'foulmouthed',
                        'foxy',
                        'fraudulent',
                        'freak',
                        'freakin',
                        'freakin',
                        'freaking',
                        'freaks',
                        'fricking',
                        'friggen',
                        'friggin',
                        'friggin',
                        'fringin',
                        'frucking',
                        'fuc***',
                        'fuck',
                        'fuck-up',
                        'fucka',
                        'fuckass',
                        'fuckbag',
                        'fuckboy',
                        'fuckbrain',
                        'fuckbutt',
                        'fuckbutter',
                        'fucked',
                        'fucker',
                        'fuckers',
                        'fuckersucker',
                        'fuckface',
                        'fuckhead',
                        'fuckheads',
                        'fuckhole',
                        'fuckin',
                        'fucking',
                        'fuckings',
                        'fuckingshitmotherfucker',
                        'fuckme ',
                        'fucknut',
                        'fucknutt',
                        'fuckoff',
                        'fucks',
                        'fuckshitcunt',
                        'fuckstick',
                        'fucktard',
                        'fucktart',
                        'fuckup',
                        'fuckwad',
                        'fuckwhit',
                        'fuckwit',
                        'fuckwitt',
                        'fudge packer',
                        'fudgepacker',
                        'fuhrer',
                        'fuk',
                        'fuker',
                        'fukin',
                        'fukker',
                        'fukkin',
                        'fuks',
                        'fukwhit',
                        'fukwit',
                        'fumpy',
                        'furhrer',
                        'furkin',
                        'fux',
                        'fux0r',
                        'fuxcking',
                        'fvcked',
                        'fyou',
                        'gag',
                        'gangbang',
                        'gangbanged ',
                        'gangbangs ',
                        'gangsters',
                        'garbage',
                        'gay',
                        'gay-haters',
                        'gayass',
                        'gaybob',
                        'gaydo',
                        'gayfuck',
                        'gayfuckist',
                        'gayhaters',
                        'gaylord',
                        'gays',
                        'gaysex',
                        'gaytard',
                        'gaywad',
                        'gaza',
                        'genitals',
                        'genocidal',
                        'genocide',
                        'gluttons',
                        'goatse',
                        'god-dam',
                        'god-damned',
                        'goddammit',
                        'goddamn',
                        'goddamned',
                        'goddamnit',
                        'goldigger',
                        'gomer',
                        'gooch',
                        'goof',
                        'goofball',
                        'goofiest',
                        'goofs',
                        'goofy',
                        'gook',
                        'goon',
                        'gosh-darned',
                        'goshdarned',
                        'gra',
                        'greenies',
                        'grifter',
                        'grifters',
                        'gringo',
                        'gross',
                        'grumpy',
                        'guido',
                        'h-o-l-e',
                        'hag',
                        'hags',
                        'hairy',
                        'handjob',
                        'hard on',
                        'hardcoresex ',
                        'hate-filled',
                        'hate-on',
                        'hatefilled',
                        'hateful',
                        'hateon',
                        'hating',
                        'headless',
                        'hed',
                        'heeb',
                        'heinous',
                        'hell',
                        'hellholes',
                        'hermit',
                        'heroin',
                        'heshe',
                        'highs',
                        'hippies',
                        'hit-man',
                        'hitler',
                        'ho',
                        'hoar',
                        'hoarders',
                        'hoare',
                        'hoe',
                        'hoer',
                        'hog',
                        'hogs',
                        'homo',
                        'homodumbshit',
                        'homophobe',
                        'homophobic',
                        'homosexual',
                        'homosexualists',
                        'homosexuals',
                        'honkey',
                        'hooker',
                        'hookers',
                        'hopeless',
                        'hore',
                        'horniest',
                        'horny',
                        'horrific',
                        'horrified',
                        'horseshit',
                        'hotsex',
                        'humbug',
                        'humping',
                        'hypocrats',
                        'hypocrisy',
                        'hypocrite',
                        'hypocrites',
                        'hypocritica',
                        'hypocritical',
                        'hypocrits',
                        'i*d*i*o*t*s',
                        'ickers',
                        'icky',
                        'idiocies',
                        'idiocracy',
                        'idiocy',
                        'idiot',
                        "idiot's",
                        'idiota',
                        'idioters',
                        'idiotic',
                        'idiototic',
                        'idiotphobe',
                        'idiots',
                        'idiots',
                        'idiot�s',
                        'ignoramous',
                        'ignoramu',
                        'ignoramus',
                        'ignoranc',
                        'ignorance',
                        'ignorant',
                        'ill',
                        'ill-mannered',
                        'ill-prepared',
                        'illegals',
                        'illiterate',
                        'illiterates',
                        'illmannered',
                        'illogic',
                        'illprepared',
                        'imbecile',
                        'imbeciles',
                        'imbecilic',
                        'immature',
                        'immoral',
                        'immorality',
                        'impostor',
                        'inane',
                        'incest',
                        'incompetence',
                        'incompetent',
                        'incompetents',
                        'incurables',
                        'inept',
                        'infantile',
                        'inferior',
                        'infidels',
                        'infiltrator',
                        'insan',
                        'insane',
                        'insanity',
                        'insecure',
                        'insidiously',
                        'insolent',
                        'invader',
                        'invaders',
                        'invading',
                        'invasion',
                        'irrational',
                        'isis',
                        'isl',
                        'islamaphobe',
                        'islamaphobeliar',
                        'islamic',
                        'islamists',
                        'islamophobe',
                        'islamophobia',
                        'jack***',
                        'jack-off ',
                        'jacka**',
                        'jackass',
                        'jackasses',
                        'jackoff',
                        'jagoff',
                        'jan',
                        'janusfaced',
                        'jap',
                        'jerk',
                        'jerk off',
                        'jerk-off ',
                        'jerkass',
                        'jerkoffs',
                        'jerks',
                        'jigaboo',
                        'jingoistic',
                        'jism',
                        'jiz ',
                        'jizm ',
                        'jizz',
                        'jungle bunny',
                        'junglebunny',
                        'junk',
                        'junky',
                        'kawk',
                        'kick',
                        'kicked',
                        'kickin',
                        'kicking',
                        'kickpunch',
                        'kicks',
                        'kickthem',
                        'kidnap',
                        'kidnappers',
                        'kike',
                        'kill',
                        'killable',
                        'killer',
                        'killers',
                        'killing',
                        'killings',
                        'kills',
                        'kkk',
                        'klan',
                        'knave',
                        'knifed',
                        'knob',
                        'knob end',
                        'knobead',
                        'knobed',
                        'knobend',
                        'knobhead',
                        'knobjocky',
                        'knobjokey',
                        'know-it-alls',
                        'knowitalls',
                        'knuckdraggers',
                        'knucklehead',
                        'knuckleheads',
                        'kock',
                        'kondum',
                        'kondums',
                        'kooch',
                        'kook',
                        'kootch',
                        'kraut',
                        'ku-ku-klowns',
                        'kukuklowns',
                        'kum',
                        'kummer',
                        'kumming',
                        'kums',
                        'kunilingus',
                        'kunt',
                        'kyke',
                        'l',
                        'l3i+ch',
                        'l3itch',
                        'labia',
                        'lackeys',
                        'lame',
                        'lameass',
                        'lapdog',
                        'lardass',
                        'laughable',
                        'laziness',
                        'lazy',
                        'leeches',
                        'lefties',
                        'leftist',
                        'leftists',
                        'lesbian',
                        'lesbians',
                        'lesbo',
                        'lezzie',
                        'liar',
                        'liars',
                        'libbies',
                        'libtards',
                        'lickers',
                        'licking',
                        'licks',
                        'liespropag',
                        'lmao',
                        'lmfao',
                        'loathsome',
                        'lon',
                        'lone',
                        'loon',
                        'looney',
                        'loonies',
                        'loony',
                        'looooooosers',
                        'looser',
                        'loosers',
                        'loozers',
                        'loser',
                        'loser5',
                        'losers',
                        'loudmouth',
                        'lousy',
                        'low-iq',
                        'lowiq',
                        'lowlife',
                        'loyalists',
                        'lucife',
                        'lucifer',
                        'ludicrous',
                        'ludicrously',
                        'lunatic',
                        'lunatics',
                        'lust',
                        'lusting',
                        'lying',
                        'm0f0',
                        'm0fo',
                        'm45terbate',
                        'ma5terb8',
                        'ma5terbate',
                        'machiavellian',
                        'mad',
                        'madmen',
                        'madness',
                        'mafia',
                        'maggots',
                        'maimed',
                        'maladroit',
                        'malignant',
                        'mamparas',
                        'man-boy',
                        'manbearpig',
                        'manboy',
                        'manchild',
                        'maniacal',
                        'maniacs',
                        'manipulating',
                        'manure',
                        'masochist',
                        'mass-murdering',
                        'massacre',
                        'massmurdering',
                        'master-bate',
                        'masterb8',
                        'masterbat*',
                        'masterbat3',
                        'masterbate',
                        'masterbation',
                        'masterbations',
                        'masturbate',
                        'masturbation',
                        'mcfagget',
                        'mean-spirited',
                        'mean-spiritedness',
                        'meanspirited',
                        'meanspiritedness',
                        'mediocre',
                        'mediocrity',
                        'mental',
                        'mentally',
                        'messed',
                        'meterosexual',
                        'meth',
                        'methhead',
                        'mick',
                        'midget',
                        'midgets',
                        'mierda',
                        'milksop',
                        'minder',
                        'mindless',
                        'minge',
                        'miserable',
                        'miserably',
                        'misogynic',
                        'misogynist',
                        'misogynistic',
                        'misogynists',
                        'mitch',
                        'mo-fo',
                        'mof0',
                        'mofo',
                        'molested',
                        'molesters',
                        'momans',
                        'monster',
                        'monsters',
                        'moochers',
                        'moron',
                        "moron's",
                        'moronic',
                        'morons',
                        'mothafuck',
                        'mothafucka',
                        'mothafuckas',
                        'mothafuckaz',
                        'mothafucked ',
                        'mothafucker',
                        'mothafuckers',
                        'mothafuckin',
                        'mothafuckin',
                        'mothafucking ',
                        'mothafuckings',
                        'mothafucks',
                        'mother fucker',
                        'motherfuck',
                        'motherfucked',
                        'motherfucker',
                        'motherfuckers',
                        'motherfuckin',
                        'motherfucking',
                        'motherfuckings',
                        'motherfuckka',
                        'motherfucks',
                        'mouthbreathing',
                        'mudered',
                        'muff',
                        'muffdiver',
                        'muffed',
                        'munging',
                        'murder',
                        'murdered',
                        'murderer',
                        'murderers',
                        'murdering',
                        'murders',
                        'muslim',
                        'muslimists',
                        'muslims',
                        'mutha',
                        'muthafecker',
                        'muthafuckker',
                        'muther',
                        'mutherfucker',
                        'mysogynistic',
                        'n1gga',
                        'n1gger',
                        'naked',
                        'narcisist',
                        'narcissism',
                        'narcissist',
                        'narcissistic',
                        'narcissists',
                        'nards',
                        'narrow-minded',
                        'narrowminded',
                        'nastiest',
                        'nasty',
                        'nauseating',
                        'nazi',
                        'nazi-like',
                        'naziand',
                        'nazilike',
                        'nazis',
                        'neanderthals',
                        'negligence',
                        'negligent',
                        'negro',
                        'neo-nazis',
                        'neonazis',
                        'neutered',
                        'nigaboo',
                        'niger',
                        'nigers',
                        'nigg3r',
                        'nigg4h',
                        'nigga',
                        'niggah',
                        'niggardly',
                        'niggas',
                        'niggaz',
                        'nigger',
                        'niggers',
                        'niggers ',
                        'niglet',
                        'nincompoop',
                        'nipples',
                        'nitwit',
                        'nob',
                        'nob jokey',
                        'nobhead',
                        'nobjocky',
                        'nobjokey',
                        'numb-nuts',
                        'numbnuts',
                        'numbskull',
                        'nut',
                        'nut sack',
                        'nutcase',
                        'nutjob',
                        'nutjobs',
                        'nuts',
                        'nutsack',
                        'nutter',
                        'nutters',
                        'nutty',
                        'oafish',
                        'obnoxious',
                        'obtuse',
                        'octopussy',
                        'odious',
                        'offender',
                        'offenders',
                        'omg',
                        'opportunist',
                        'opportunistic',
                        'opportunists',
                        'oppresser',
                        'oppressive',
                        'oral',
                        'orgasim ',
                        'orgasims ',
                        'orgasm',
                        'orgasms ',
                        'orgy',
                        'ovaries',
                        'p****',
                        'p****ies',
                        'p***y',
                        'p*ssies',
                        'p*ssy',
                        'p0rn',
                        'paf',
                        'paki',
                        'panooch',
                        'panties',
                        'paranoid',
                        'parasite',
                        'parasites',
                        'parasitic',
                        'passive-aggresive',
                        'passiveaggresive',
                        'patheti',
                        'pathetic',
                        'pathetically',
                        'pawn',
                        'peanuthead',
                        'pecker',
                        'peckerhead',
                        'pedo',
                        'pedophile',
                        'pedophiles',
                        'pedophilia',
                        'pee',
                        'pegged',
                        'pendejo',
                        'penetrated',
                        'penetrates',
                        'penetrating',
                        'penis',
                        'penis-extension',
                        'penisbanger',
                        'penisextension',
                        'penisfucker',
                        'penispuffer',
                        'peo',
                        'perjurs',
                        'perpetrators',
                        'pervert',
                        'perverted',
                        'perverts',
                        'pesky',
                        'petulance',
                        'petulant',
                        'petullent',
                        'phonesex',
                        'phony',
                        'phuck',
                        'phuk',
                        'phuked',
                        'phuking',
                        'phukked',
                        'phukking',
                        'phuks',
                        'phuq',
                        'pig',
                        'pig-headed',
                        'pigfucker',
                        'piggish',
                        'pigheaded',
                        'piglets',
                        'pigs',
                        'pimpis',
                        'pinocchio',
                        'piss',
                        'pissed',
                        'pissed off',
                        'pisser',
                        'pissers',
                        'pisses',
                        'pisses ',
                        'pissflaps',
                        'pissin ',
                        'pissing',
                        'pissoff ',
                        'polesmoker',
                        'pollock',
                        'pompas',
                        'pompous',
                        'poo',
                        'poof',
                        'poon',
                        'poonani',
                        'poonany',
                        'poontang',
                        'poop',
                        'poopy',
                        'porch monkey',
                        'porchmonkey',
                        'porn',
                        'porno',
                        'pornography',
                        'pornos',
                        'potheads',
                        'potty',
                        'predator',
                        'predators',
                        'pretentious',
                        'prick',
                        'pricks ',
                        'primitive',
                        'pron',
                        'prostitute',
                        'prostitutes',
                        'prostitution',
                        'pseudo-human',
                        'pseudohuman',
                        'psycho',
                        'psycho-killers',
                        'psychokillers',
                        'psychopath',
                        'psychopaths',
                        'psychotic',
                        'pu*ssy',
                        'pube',
                        'pucker',
                        'puke',
                        'puking',
                        'punanny',
                        'punch',
                        'punched',
                        'punk',
                        'punks',
                        'punta',
                        'puppet',
                        'puppets',
                        'purp',
                        'pusse',
                        'pussi',
                        'pussies',
                        'pusssy',
                        'pussy',
                        'pussy-grabbing',
                        'pussygrabbing',
                        'pussyh',
                        'pussylicking',
                        'pussys ',
                        'puto',
                        'putrid',
                        'queef',
                        'queer',
                        'queerbait',
                        'queerhole',
                        'rabid',
                        'rabidly',
                        'racis',
                        'racism',
                        'racist',
                        'racists',
                        'radicals',
                        'rancid',
                        'rape',
                        'raped',
                        'rapes',
                        'raping',
                        'rapist',
                        'rapist-in-chief',
                        'rapistinchief',
                        'rapists',
                        'rat',
                        "rat's",
                        'rathole',
                        'rats',
                        'raving',
                        'rear',
                        'rectum',
                        'redenbacher',
                        'rediculous',
                        'redneck',
                        'reek',
                        'reich',
                        'reichwing',
                        'religious-hypocrite',
                        'religioushypocrite',
                        'renob',
                        'reproduce',
                        'reptilian',
                        'repugnant',
                        'repulsive',
                        'retard',
                        'retarded',
                        'retards',
                        'ridicule',
                        'ridiculou',
                        'ridiculous',
                        'ridiculously',
                        'ridiculousness',
                        'rimjaw',
                        'rimjob',
                        'rimming',
                        'robbed',
                        'robs',
                        'rooskies',
                        'rot',
                        'rotten',
                        'rubbish',
                        'ruining',
                        'ruski',
                        's hit',
                        's***',
                        's**t',
                        's.o.b.',
                        's_h_i_t',
                        'sabotage',
                        'sack',
                        'sacks',
                        'sadist',
                        'sanctimonious',
                        'sand nigger',
                        'sandnigger',
                        'satan',
                        "satan's",
                        'scammers',
                        'scams',
                        'schill',
                        'schlong',
                        'schmuck',
                        'schmucks',
                        'schumucks',
                        'scks',
                        'scoundrel',
                        'screw',
                        'screwed',
                        'screwing',
                        'scroat',
                        'scrote',
                        'scrotum',
                        'scrub',
                        'scu',
                        'scum',
                        'scum-sucking',
                        'scumbag',
                        'scumbags',
                        'scummy',
                        'scumsucking',
                        'sed',
                        'self-fornication',
                        'self-loving',
                        'self-satisfied',
                        'selffornication',
                        'selfish',
                        'selfloving',
                        'selfsatisfied',
                        'semen',
                        'senile',
                        'sex',
                        'sexism',
                        'sexist',
                        'sexists',
                        'sexual',
                        'sh!+',
                        'sh!t',
                        'sh**',
                        'sh**load',
                        'sh*t',
                        'sh1t',
                        'shag',
                        'shagger',
                        'shaggin',
                        'shagging',
                        'sham',
                        'shameless',
                        'sheeps',
                        'shemale',
                        'shi*ty',
                        'shi+',
                        'shifty',
                        'shills',
                        'shit',
                        'shit-heads',
                        'shitass',
                        'shitbag',
                        'shitbagger',
                        'shitbrains',
                        'shitbreath',
                        'shitcanned',
                        'shitcunt',
                        'shitdick',
                        'shite',
                        'shited',
                        'shitey',
                        'shitface',
                        'shitfaced',
                        'shitfuck',
                        'shitfull',
                        'shithead',
                        'shitheads',
                        'shithole',
                        'shithouse',
                        'shiting',
                        'shitings',
                        'shits',
                        'shitspitter',
                        'shitstain',
                        'shitted',
                        'shitter',
                        'shitters ',
                        'shittiest',
                        'shitting',
                        'shittings',
                        'shitty',
                        'shitty ',
                        'shiz',
                        'shiznit',
                        'shoot',
                        'shooter',
                        'shootings',
                        'shootout',
                        'shoots',
                        'shove',
                        'shpremes',
                        'sht',
                        'sick',
                        'sickening',
                        'sickest',
                        'sickly',
                        'sicko',
                        'sickos',
                        'sillie',
                        'silliness',
                        'silly',
                        'simpleton',
                        'sissy',
                        'skank',
                        'skeet',
                        'skinheads',
                        'skinned',
                        'skullfuck',
                        'slap',
                        'slave',
                        'sleaze',
                        'sleazebag',
                        'sleazy',
                        'slug',
                        'slugs',
                        'slut',
                        'slutbag',
                        'sluts',
                        'small-minded',
                        'smallminded',
                        'smeg',
                        'smegma',
                        'smells',
                        'smelly',
                        'smucks',
                        'smut',
                        'snake',
                        'snakes',
                        'snatch',
                        'snot',
                        'snowflake',
                        'snowflakes',
                        'sobs',
                        'socio-pathic',
                        'sociopath',
                        'sociopathic',
                        'sociopaths',
                        'son-of-a-bitch',
                        'sore-loser',
                        'soreloser',
                        'spac',
                        'spewed',
                        'spic',
                        'spick',
                        'spineless',
                        'splooge',
                        'spook',
                        'spout',
                        'spouting',
                        'spouts',
                        'spunk',
                        'spurt',
                        'squirt',
                        'stabs',
                        'stalker',
                        'stank',
                        'std',
                        'steal',
                        'steals',
                        'stench',
                        'stewpid',
                        'stfu',
                        'stink',
                        'stinker',
                        'stinking',
                        'stinks',
                        'stinky',
                        'stone-stupid',
                        'stoned',
                        'stonestupid',
                        'stooges',
                        'stooooopid',
                        'strangle',
                        'strippers',
                        'stupdity',
                        'stupi',
                        'stupib',
                        'stupid',
                        'stupida',
                        'stupider',
                        'stupidest',
                        'stupidestpresidentever',
                        'stupidfat',
                        'stupididty',
                        'stupidiest',
                        'stupidiity',
                        'stupidis',
                        'stupidism',
                        "stupidit's",
                        'stupidity',
                        'stupiditywhy',
                        'stupidly',
                        'stupids',
                        'stupidselfish',
                        'succcccccccccccccckkkkkk',
                        'suck',
                        'suckass',
                        'sucked',
                        'suckees',
                        'sucker',
                        'suckered',
                        'suckers',
                        'suckin',
                        'sucking',
                        'sucks',
                        'sucky',
                        'suffer',
                        'suicide',
                        'supremacist',
                        'supremacists',
                        'swine',
                        'sycophant',
                        'sycophantic',
                        'sycophants',
                        't1tt1e5',
                        't1tties',
                        'tard',
                        'teats',
                        'teets',
                        'teez',
                        'terrible',
                        'terribly',
                        'terrorist',
                        'terrorists',
                        'terrorize',
                        'terrorizing',
                        'testical',
                        'testicle',
                        'testicles',
                        'testicules',
                        'thief',
                        'thieves',
                        'thieving',
                        'thin-skinned',
                        'thinskinned',
                        'thoughtless',
                        'threatened',
                        'threats',
                        'thug',
                        'thugs',
                        'thundercunt',
                        'tit',
                        'tit-sucking',
                        'titfuck',
                        'tits',
                        'titsucking',
                        'titt',
                        'tittie5',
                        'tittiefucker',
                        'titties',
                        'tittyfuck',
                        'tittywank',
                        'titwank',
                        'tonto',
                        'torment',
                        'torture',
                        'tosser',
                        'traitor',
                        'traitorous',
                        'tramp',
                        'tran',
                        'trannies',
                        'trans',
                        'transgender',
                        'transgenders',
                        'transvestite',
                        'trappers',
                        'trash',
                        'trash-talk',
                        'trashtalk',
                        'treacherous',
                        'treasonous',
                        'trickster',
                        'tripe',
                        'trol',
                        'troll',
                        'trolls',
                        'trump-as-useful-idiot',
                        'trump-humpers',
                        'trump-suckers',
                        'trumpasusefulidiot',
                        'trumpean',
                        'trumphumpers',
                        'trumpkin',
                        'trumplers',
                        'trumplodites',
                        'trumpster',
                        "trumpster's",
                        'trumpsters',
                        'trumpsuckers',
                        'tupid',
                        'turd',
                        'tw4t',
                        'twaddle',
                        'twat',
                        'twathead',
                        'twatlips',
                        'twats',
                        'twatty',
                        'twatwaffle',
                        'twerps',
                        'twit',
                        'two-faces',
                        'twofaced',
                        'twunt',
                        'twunter',
                        'tyrant',
                        'uck',
                        'ugly',
                        'un-deserving',
                        'un-educatedoops',
                        'un-smart',
                        'unapologetic',
                        'unappealing',
                        'uncaring',
                        'unclefucker',
                        'undependable',
                        'underhand',
                        'undeserving',
                        'uneducated',
                        'unethical',
                        'unfaithful',
                        'ungrateful',
                        'uninformed',
                        'unintelligent',
                        'unpatriotic',
                        'unpayable',
                        'unpopular',
                        'unrational',
                        'unredemptive',
                        'unruly',
                        'unscrupulous',
                        'unsmart',
                        'unstable',
                        'untermensch',
                        'unthank',
                        'unthinking',
                        'untruthful',
                        'unwashed',
                        'unwelcome',
                        'urine',
                        'useles',
                        'useless',
                        'v14gra',
                        'v1gra',
                        'va-j-j',
                        'vacuous',
                        'vag',
                        'vagabond',
                        'vagina',
                        'vagrancy',
                        'vajayjay',
                        'vandalize',
                        'vanity',
                        'vapidity',
                        'vengeful',
                        'vermin',
                        'viagra',
                        'vicious',
                        'viciously',
                        'vile',
                        'vixen',
                        'vjayjay',
                        'voetsek',
                        'vomit',
                        'vultures',
                        'vulva',
                        'w00se',
                        'wacko',
                        'wackos',
                        'wang',
                        'wank',
                        'wanker',
                        'wankjob',
                        'wanky',
                        'warmongers',
                        'weak',
                        'weasel',
                        'weenie',
                        'weird',
                        'weirdo',
                        'wetback',
                        'whack',
                        'whackjob',
                        'whacko',
                        'whiner',
                        'whiners',
                        'whinny',
                        'whiny',
                        'white-trash',
                        'whitefragilitycankissmyass',
                        'whitetrash',
                        'whiteys',
                        'whoar',
                        'whore',
                        'whorebag',
                        'whoreface',
                        'whores',
                        'whres',
                        'willies',
                        'willy',
                        'wimp',
                        'wimpy',
                        'witch',
                        'witless',
                        'woman-hating',
                        'womanhating',
                        'wop',
                        'workshy',
                        'worthless',
                        'wretched',
                        'wtf',
                        'wwiii',
                        'xenophobe',
                        'xenophobes',
                        'xenophobia',
                        'xenophobic',
                        'xrated',
                        'xxx',
                        'yada',
                        'yates',
                        'yuck',
                        'zealot',
                        'zealots',
                        'zombies'
                        ]  
    
    for word in words:
        if word in toxic_indicators:
            toxic_words.append(word)
    
    return toxic_words

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/api')
def api_docs():
    return render_template('api.html')

@app.route('/about')
def about():
    return render_template('about.html')

@app.route('/api/keys', methods=['POST'])
def create_api_key():
    data = request.json
    tier = data.get('tier', 'free')
    
    if tier not in ['free', 'basic', 'premium', 'enterprise']:
        return jsonify({'error': 'Invalid tier'}), 400
        
    key = generate_api_key(tier)
    return jsonify({
        'api_key': key,
        'tier': tier,
        'daily_limit': api_keys[key].daily_limit
    })

@app.route('/api/analyze', methods=['POST'])
@require_api_key
def analyze():
    try:
        data = request.json
        text = data['text']
        
        # Detect language
        source_lang = detect_language(text) #as i removed this and using auto detect we no need this any more, but i left it
        
        # Translate if not in English
        english_text = translate_to_english(text, source_lang) # source lang not needed as i removed and used auto src but 
        
        # Preprocess the text
        processed_text = preprocess_text(english_text) #refer below line
        
        # Prepare sequence
        sequence = prepare_sequence(processed_text, tokenizer) #tensorflow needed this sequence and before we need to proccess text and get token from tokenizer file
        
        # Get prediction
        prediction = model.predict(sequence)
        
        # Get toxic words and suggestions
        toxic_words = get_toxic_words(english_text, prediction[0]) #here it will get abusive and hate ori words from get_toxic_words function.
        suggestions = get_alternative_suggestions(english_text, toxic_words) #this will find alternate words to the ori toxic_words.
        
        # Prepare response, as same as emit below
        response = {
            'original_text': text,
            'source_language': source_lang,
            'english_translation': english_text if source_lang != 'en' else None,
            'prediction': {
                'hate_speech': float(prediction[0][0]),
                'offensive_language': float(prediction[0][1]),
                'neither': float(prediction[0][2])
            },
            'toxic_words': toxic_words,
            'suggestions': suggestions
        }
        
        return jsonify(response)
    
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@socketio.on('analyze_text')
def handle_realtime_analysis(data):
    try:
        text = data['text']
        if len(text.strip()) == 0:
            return
        
        # Detect language, i dont want to remove old one so i left it, but no use of it as of now as we now changed to auto detect
        source_lang = detect_language(text)
        
        # Translate if not in English - firstly i have used hardcoded src lang, but now i have updated to auto detect language
        english_text = translate_to_english(text, source_lang)
        
        # Preprocess the text
        processed_text = preprocess_text(english_text)
        
        # Prepare sequence
        sequence = prepare_sequence(processed_text, tokenizer)
        
        # Get prediction
        prediction = model.predict(sequence)
        
        # Get toxic words and suggestions
        toxic_words = get_toxic_words(english_text, prediction[0]) #here it will get abusive and hate ori words from get_toxic_words function.
        suggestions = get_alternative_suggestions(english_text, toxic_words) #this will find alternate words to the ori toxic_words.
        
        # Emit results back to client, if we use api or direct implementation on frontend, we use this formar as result/response
        emit('analysis_results', {
            'original_text': text,
            'source_language': source_lang,
            'english_translation': english_text if source_lang != 'en' else None,
            'prediction': {
                'hate_speech': float(prediction[0][0]),
                'offensive_language': float(prediction[0][1]),
                'neither': float(prediction[0][2])
            },
            'toxic_words': toxic_words,
            'suggestions': suggestions
        })
        
    except Exception as e:
        emit('analysis_error', {'error': str(e)})

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 7200))
    print(f"Starting Hate Speech Detection App on port {port}...")
    print(f"Access the application at: http://localhost:{port}")
    
    try:
        # Try SocketIO first for full WebSocket support, so we casn have realtime stats
        print("Starting with SocketIO support...")
        socketio.run(app, host='0.0.0.0', port=port, debug=False, allow_unsafe_werkzeug=True)
    except Exception as e:
        print(f"SocketIO failed: {e}")
        print("Falling back to regular Flask (limited real-time features)...")
        # Fallback to regular Flask, if socket fails we can use regular flask but works without sockerd we need have to enter mannually
        app.run(host='0.0.0.0', port=port, debug=False)
